name: qr_code_scanner
description: Local override for qr_code_scanner
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.qrcodescanner
        pluginClass: QrCodeScannerPlugin
      ios:
        pluginClass: QrCodeScannerPlugin
