// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChdXzY_u8K9yerPf63MmtPPiGxmU6ef5I',
    appId: '1:807960477424:android:8b8b9f64b5999ca5054c35',
    messagingSenderId: '807960477424',
    projectId: 'gostore-aad67',
    storageBucket: 'gostore-aad67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX3ZjvxldgbBJqnu0eJvqjoCTow1cpjaM',
    appId: '1:807960477424:ios:9f58369f172c9c78054c35',
    messagingSenderId: '807960477424',
    projectId: 'gostore-aad67',
    storageBucket: 'gostore-aad67.firebasestorage.app',
    iosClientId: '807960477424-h03ao3bi7oi3m56334bca7gfmdb38k8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.gostore',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_BYmjWPTGq86OvjD91ew1st0G1oAuDLY',
    appId: '1:807960477424:web:d4be0f48789b5acf054c35',
    messagingSenderId: '807960477424',
    projectId: 'gostore-aad67',
    authDomain: 'gostore-aad67.firebaseapp.com',
    storageBucket: 'gostore-aad67.firebasestorage.app',
    measurementId: 'G-SX90SF3KVY',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX3ZjvxldgbBJqnu0eJvqjoCTow1cpjaM',
    appId: '1:807960477424:ios:9f58369f172c9c78054c35',
    messagingSenderId: '807960477424',
    projectId: 'gostore-aad67',
    storageBucket: 'gostore-aad67.firebasestorage.app',
    iosClientId: '807960477424-h03ao3bi7oi3m56334bca7gfmdb38k8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.gostore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_BYmjWPTGq86OvjD91ew1st0G1oAuDLY',
    appId: '1:807960477424:web:1ead8ee9982d7b28054c35',
    messagingSenderId: '807960477424',
    projectId: 'gostore-aad67',
    authDomain: 'gostore-aad67.firebaseapp.com',
    storageBucket: 'gostore-aad67.firebasestorage.app',
    measurementId: 'G-ZS40R1FBZT',
  );

}