name: google_sign_in_android
description: Local override for google_sign_in_android
version: 6.2.0
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in_platform_interface: ^2.3.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.googlesignin
        pluginClass: GoogleSignInPlugin
