name: local_auth
description: Custom local_auth override
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.local_auth
        pluginClass: LocalAuthPlugin
