name: local_auth_android
description: Local override of local_auth_android plugin
version: 1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.localauth
        pluginClass: LocalAuthPlugin

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  local_auth_platform_interface: ^1.0.10
