name: device_info_plus
description: Flutter plugin providing detailed device information. Locally overridden for Kotlin + Gradle compatibility.
version: 10.0.0+1
homepage: https://plus.fluttercommunity.dev
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.deviceinfo
        pluginClass: DeviceInfoPlusPlugin
      ios:
        pluginClass: FLTDeviceInfoPlusPlugin
      macos:
        pluginClass: FLTDeviceInfoPlusPlugin
      linux:
        pluginClass: DeviceInfoPlusPlugin
      windows:
        pluginClass: DeviceInfoPlusWindowsPlugin
      web:
        default_package: device_info_plus_web

dependencies:
  flutter:
    sdk: flutter
  device_info_plus_platform_interface: ^5.0.0
  device_info_plus_linux: ^5.0.0
  device_info_plus_macos: ^5.0.0
  device_info_plus_windows: ^5.0.0
  device_info_plus_web: ^5.0.0
  plugin_platform_interface: ^2.1.6
  meta: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^14.0.0

topics:
  - device
  - platform
  - information
  - android
